use strum::{Display, EnumIter, EnumString, IntoStaticStr};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumString, Display, IntoStaticStr, EnumIter)]
pub enum DiagnosticCode {
    ParseError,
    CanonicalSpellingKeywords,
    ConsecutiveEmptyLines,
    MultilinePreprocessorInstruction,
    LineLength,
    MissingSpace,
    OneStatementPerLine,
    SemicolonPresence,
    SpaceAtStartComment,
    IncorrectLineBreak,
    IncorrectUseOfStrTemplate,
    ExtraCommas,
    CommentedCode,
    EmptyCodeBlock,
    EmptyRegion,
    EmptyStatement,
    UnreachableCode,
    CodeBlockBeforeSub,
    CodeOutOfRegion,
    MagicNumber,
    MagicDate,
    YoLetterUsage,
    LatinAndCyrillicSymbolInWord,
    InvalidCharacterInFile,
    DoubleNegatives,
    NestedTernaryOperator,
    PostfixAccessOnExpression,
    NonExportMethodsInApiRegion,
    TernaryOperatorUsage,
    UnaryPlusInConcatenation,
    UselessTernaryOperator,
    BadWords,
    DuplicateStringLiteral,
    DuplicateRegion,
    NonStandardRegion,
    DuplicatedInsertionIntoCollection,
    ExcessiveAutoTestCheck,
    IdenticalExpressions,
    IfElseDuplicatedCodeBlock,
    IfElseDuplicatedCondition,
    IfElseIfEndsWithElse,
    MultilingualStringHasAllDeclaredLanguages,
    MultilingualStringUsingWithTemplate,
    NestedConstructorsInStructureDeclaration,
    NestedFunctionInParameters,
    Typo,

    AllFunctionPathMustHaveReturn,
    FunctionShouldHaveReturn,
    ProcedureReturnsValue,
    FunctionReturnsSamePrimitive,
    FunctionNameStartsWithGet,
    TooManyReturns,
    NumberOfParams,
    NumberOfOptionalParams,
    NumberOfValuesInStructureConstructor,
    OrderOfParams,
    MissedRequiredParameter,
    FunctionOutParameter,
    UnusedParameters,
    MissingParameterDescription,
    MissingReturnedValueDescription,
    ReservedParameterNames,
    ReservedWordAsMethodName,
    RewriteMethodParameter,
    UnusedLocalVariable,
    UnusedLocalMethod,
    ExportVariables,
    MissingVariablesDescription,
    SelfAssign,
    ThisObjectAssign,
    CyclomaticComplexity,
    CognitiveComplexity,
    NestedStatements,
    MethodSize,
    IfConditionComplexity,
    MissingCodeTryCatchEx,
    MissingTempStorageDeletion,
    MissingTemporaryFileDeletion,
    MisplacedLoopControl,
    UseLessForEach,
    UsingGoto,
    BeginTransactionBeforeTryCatch,
    CodeAfterAsyncCall,
    CommitTransactionOutsideTryCatch,
    CompilationDirectiveLost,
    CompilationDirectiveNeedLess,
    CreateQueryInCycle,
    DataExchangeLoading,
    DeletingCollectionItem,
    SelfInsertion,
    SeveralCompilerDirectives,
    StyleElementConstructors,
    DeprecatedPlatformApi,
    DeprecatedMethodCall,
    DisableSafeMode,
    ExecuteExternalCode,
    ExecuteExternalCodeInCommonModule,
    ExternalAppStarting,
    FileSystemAccess,
    OSUsersMethod,
    TempFilesDir,
    FormDataToValue,
    GetFormMethod,
    GlobalContextMethodCollision8312,
    GlobalContextMethodConflict,
    InternetAccess,
    IsInRoleMethod,
    PairingBrokenTransaction,
    WrongUseOfRollbackTransactionMethod,
    TimeoutsInExternalResources,
    TryNumber,
    UnknownPreprocessorSymbol,
    UnsafeSafeModeMethodCall,
    UsageWriteLogEvent,
    UseSystemInformation,
    UsingCancelParameter,
    UsingExternalCodeTools,
    UsingFindElementByString,
    UsingHardcodeNetworkAddress,
    UsingHardcodePath,
    UsingHardcodeSecretInformation,
    UsingModalWindows,
    UsingObjectNotAvailableUnix,
    UsingSynchronousCalls,
    UsingServiceTag,
    UsingThisForm,
    WrongUseFunctionProceedWithCall,

    WrongHttpServiceHandler,
    WrongWebServiceHandler,
    WrongDataPathForFormElements,
    PublicMethodsDescription,
    CachedPublic,
    CommandModuleExportMethods,
    CommonModuleAssign,
    CommonModuleInvalidType,
    CommonModuleMissingAPI,
    CommonModuleNameCached,
    CommonModuleNameClient,
    CommonModuleNameClientServer,
    CommonModuleNameFullAccess,
    CommonModuleNameGlobal,
    CommonModuleNameGlobalClient,
    CommonModuleNameServerCall,
    CommonModuleNameWords,
    DenyIncompleteValues,
    ForbiddenMetadataName,
    MetadataObjectNameLength,
    MissingCommonModuleMethod,
    MissingEventSubscriptionHandler,
    OrdinaryAppSupport,
    PrivilegedModuleMethodCall,
    ProtectedModule,
    RedundantAccessToObject,
    SameMetadataObjectAndChildNames,
    ScheduledJobHandler,
    ServerCallsInFormEvents,
    ServerSideExportFormMethod,
    SetPermissionsForNewObjects,
    SetPrivilegedMode,
    TransferringParametersBetweenClientAndServer,
    UnsafeFindByCode,
    WeavingAnnotationNotApplicable,
    WeavingSignatureMismatch,

    UnresolvedName,
    UnresolvedMethodCall,
    UnresolvedBareCall,
    MismatchedArgCount,
    TypeMismatch,
    TypeMismatchByDocComment,
    UnresolvedField,
    ReadOnlyPropertyAssignment,
    GlobalPropertyNotWritable,
    UnavailableInEnvironment,
    PlatformMemberNewerThanMinVersion,
    PlatformMemberHiddenByCompatibilityMode,
    ModuleAccessibility,

    AmbiguousFieldInQuery,
    AssignAliasFieldsInQuery,
    DuplicateAliasInQuery,
    FieldsFromJoinsWithoutIsNull,
    FullOuterJoinQuery,
    IncorrectUseLikeInQuery,
    JoinWithSubQuery,
    JoinWithVirtualTable,
    LogicalOrInJoinQuerySection,
    LogicalOrInTheWhereSectionOfQuery,
    MultilineStringInQuery,
    QueryNestedFieldsByDot,
    QueryParseError,
    QueryToMissingMetadata,
    UnknownFieldInQuery,
    UnlimitedLengthStringUsageInQuery,
    RefOveruse,
    SelectTopWithoutOrderBy,
    UnionAll,
    UsingLikeInQuery,
    VirtualTableCallWithoutParameters,

    UnknownSuppressionCode,
    SuppressionWithoutCode,
}

impl DiagnosticCode {
    pub fn as_str(&self) -> &'static str {
        (*self).into()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    #[test]
    fn test_as_str() {
        assert_eq!(DiagnosticCode::LineLength.as_str(), "LineLength");
        assert_eq!(DiagnosticCode::EmptyCodeBlock.as_str(), "EmptyCodeBlock");
    }

    #[test]
    fn test_from_str() {
        assert_eq!(DiagnosticCode::from_str("LineLength"), Ok(DiagnosticCode::LineLength));
        assert_eq!(DiagnosticCode::from_str("EmptyCodeBlock"), Ok(DiagnosticCode::EmptyCodeBlock));
        assert!(DiagnosticCode::from_str("UnknownCode").is_err());
    }

    #[test]
    fn test_display() {
        assert_eq!(format!("{}", DiagnosticCode::LineLength), "LineLength");
    }
}
